spring:
  security:
    oauth2:
      client:
        provider:
          my-keycloak-provider:
            issuer-uri: http://localhost:8080/realms/My-Realm
        registration:
            keycloak-spring-gateway-client:
              provider: my-keycloak-provider
              client-id: spring-gateway-application
              client-secret: qku2rN9Yys9jeBfCeoX8wZbrRKJJ5pdE
              authorization-grant-type: authorization_code
              redirect_uri: "{baseUrl}/login/oauth2/code/keycloak"
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: inventory-service
          uri: http://localhost:8082
          predicates:
            - Path=/inventory/**

server:
  port: 8081




management:
  endpoints:
    web:
      exposure:
        include: "*"